build: false
clone_depth: 1
clone_folder: c:\projects\google-cloud

cache:
  - vendor -> composer.json

init:
  - SET PATH=c:\Program Files\OpenSSL;c:\tools\php;%PATH%
  - SET COMPOSER_NO_INTERACTION=1

environment:
  matrix:
    - PHP_VERSION: 5.5
    - PHP_VERSION: 5.6
    - PHP_VERSION: 7.0
      GRPC_SRC: "http://windows.php.net/downloads/pecl/releases/grpc/1.9.0/php_grpc-1.9.0-7.0-nts-vc14-x64.zip"
    - PHP_VERSION: 7.1
      GRPC_SRC: "http://windows.php.net/downloads/pecl/releases/grpc/1.9.0/php_grpc-1.9.0-7.1-nts-vc14-x64.zip"
    - PHP_VERSION: 7.2
      GRPC_SRC: "http://windows.php.net/downloads/pecl/releases/grpc/1.9.0/php_grpc-1.9.0-7.2-nts-vc15-x64.zip"

install:
  - cinst -y OpenSSL.Light
  - ps: appveyor-retry cinst --params '""/InstallDir:C:\tools\php""' --ignore-checksums -y php --version ((choco search php --exact --all-versions -r | select-string -pattern $env:PHP_VERSION | sort { [version]($_ -split '\|' | select -last 1) } -Descending | Select-Object -first 1) -replace '[php|]','')
  - ps: . .\dev\appveyor-php.ps1
  - cd c:\projects\google-cloud
  - curl --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 0 --retry-max-time 40 -o composer-setup.php https://getcomposer.org/installer
  - curl --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 0 --retry-max-time 40 -o composer-signature.sig https://composer.github.io/installer.sig
  - php -r "if (hash_file('SHA384', 'composer-setup.php') === rtrim(file_get_contents('composer-signature.sig'))) {echo 'Installer verified';unlink('composer-signature.sig');} else {echo 'Installer corrupt';unlink('composer-setup.php');unlink('composer-signature.sig');exit (1);}"
  - php .\composer-setup.php
  - php -r "unlink('composer-setup.php');"
  - php composer.phar install

test_script:
  - cd c:\projects\google-cloud
  - vendor/bin/phpunit -c phpunit.xml.dist
