on:
  push:
    branches:
      - main
    paths:
      - 'Bigtable/**'
      - '.github/workflows/emulator-system-tests-bigtable.yaml'
      - '.github/emulator/**'
  pull_request:
    paths:
      - 'Bigtable/**'
      - '.github/workflows/emulator-system-tests-bigtable.yaml'
      - '.github/emulator/**'
name: Emulator System Tests
permissions:
  contents: read
jobs:
  test:
    name: Bigtable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - run: ./.github/emulator/start-emulator.sh bigtable 522.0.0-emulators

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: pecl
          extensions: grpc

      - name: Install dependencies
        run: |
          composer config minimum-stability dev -d Bigtable/
          composer config repositories.local path "../Core" -d Bigtable
          composer require "google/cloud-core:*" -d Bigtable/

      - name: Run system tests
        run: |
          Bigtable/vendor/bin/phpunit -c Bigtable/phpunit-system.xml.dist --group bigtable
        env:
          BIGTABLE_EMULATOR_HOST: localhost:8085
          GOOGLE_CLOUD_PHP_TESTS_KEY_PATH: '.github/emulator/example-key.json'
          GOOGLE_CLOUD_PHP_WHITELIST_TESTS_KEY_PATH: '.github/emulator/example-key.json'
