on:
  push:
    branches:
      - main
    paths:
      - 'PubSub/**'
  pull_request:
    paths:
      - 'PubSub/**'
name: Run PubSub System Tests With Emulator
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: ./.github/emulator/start-emulator.sh pubsub

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: pecl
          extensions: grpc

      - name: Install dependencies
        run: |
          composer config minimum-stability dev -d PubSub/
          composer config repositories.local path "../Core" -d PubSub
          composer require "google/cloud-core:*" -d PubSub/

      - name: Run system tests
        run: |
          PubSub/vendor/bin/phpunit -c PubSub/phpunit-system.xml.dist --exclude-group gapic
        env:
          PUBSUB_EMULATOR_HOST: localhost:8085
          PROJECT_ID: my-project-id
          GOOGLE_CLOUD_PHP_TESTS_KEY_PATH: '.github/emulator/example-key.json'
          GOOGLE_CLOUD_PHP_WHITELIST_TESTS_KEY_PATH: '.github/emulator/example-key.json'
